### ISSUE TITLE
Would you like to make it available to pip?

### ISSUE THREAD

**Issue by XieXiaonan** [ndeutschmann/better_abc#1]
I think it is really useful, at least I have a circumstance to use it.
So would you mind making it available to pip? Really Thanks

**Comment by ndeutschmann** [comment]
Hi! This is something I copy pasted from stackoverflow and have tested only marginally. As a result I'd rather not reserve a name for it on PyPI, at least not yet.

In the meantime you can still install this using pip's VCS URLs:

`pip install better-abc @ git+https://github.com/ndeutschmann/better_abc@6b393a2ae82da68e85f9a960eecbbb98bfd8d143` 

will work just fine. This is actually why I created a git repo for this package ([see here](https://github.com/ndeutschmann/pytorch_flows/blob/master/requirements.txt#L3)).
